Juntando Dev na MAIN
cybalencar96/projeto_11_Linkr pull request #48
Opened 2021-09-25 14:36 UTC by cybalencar96

Alterações:

- Atualizacao da timeline a cada 15 segundos
- Compartilhar localização
- Aparecer posts apenas dos usuario seguidos
- Comentar post
- Acessar posts de hashtag e correcao de layout
- Carregamento progressivo de timeline
- Preview de link dentro do app

- Bugfixes:
        - Primeiro post aleatoria as vezes aparecia em UserPages diferentes
        - Timeline infinita renderizava posts de outras paginas ao trocar rapidamente de pagina
        - Renderização de likes

2021-09-25 16:42 UTC, sZeuSz submitted a review, later dismissed
Muito bom, velho. Só orgulho da nossa rede social quentííssima.

2021-09-26 21:35 UTC, sZeuSz approved these changes

2021-09-27 14:31 UTC, ninidora requested changes

2021-09-27 14:31 UTC, ninidora commented on src/components/shared/Card/CardStyled.js
> +    /* align-self: flex-start; */
Remover comentários

2021-09-27 14:31 UTC, ninidora approved these changes

2021-09-27 14:32 UTC, merged